# Generated by Django 5.0.6 on 2025-01-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=50)),
                ('section_info', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Packages Section',
            },
        ),
    ]
