# Generated by Django 5.0.6 on 2025-01-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages_section',
            old_name='section_info',
            new_name='first_section_info',
        ),
        migrations.RenameField(
            model_name='packages_section',
            old_name='section_title',
            new_name='first_section_title',
        ),
        migrations.AddField(
            model_name='packages_section',
            name='second_section_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='packages_section',
            name='second_section_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
