# Generated by Django 5.0.6 on 2025-01-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Section', '0002_rename_section_info_packages_section_first_section_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages_section',
            old_name='first_section_info',
            new_name='plan_info',
        ),
        migrations.RenameField(
            model_name='packages_section',
            old_name='second_section_info',
            new_name='section_info',
        ),
        migrations.RenameField(
            model_name='packages_section',
            old_name='first_section_title',
            new_name='section_title',
        ),
        migrations.RemoveField(
            model_name='packages_section',
            name='second_section_title',
        ),
        migrations.AddField(
            model_name='packages_section',
            name='plan_category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='packages_section',
            name='plan_icon',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='packages_section',
            name='plan_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='packages_section',
            name='plan_title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
