# Generated by Django 5.0.6 on 2025-01-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Section', '0003_rename_first_section_info_packages_section_plan_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages_section',
            old_name='plan_info',
            new_name='first_section_info',
        ),
        migrations.RenameField(
            model_name='packages_section',
            old_name='section_title',
            new_name='first_section_title',
        ),
        migrations.RenameField(
            model_name='packages_section',
            old_name='section_info',
            new_name='second_section_info',
        ),
        migrations.RemoveField(
            model_name='packages_section',
            name='plan_category',
        ),
        migrations.RemoveField(
            model_name='packages_section',
            name='plan_icon',
        ),
        migrations.RemoveField(
            model_name='packages_section',
            name='plan_price',
        ),
        migrations.RemoveField(
            model_name='packages_section',
            name='plan_title',
        ),
        migrations.AddField(
            model_name='packages_section',
            name='second_section_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
