# Generated by Django 5.0.6 on 2025-01-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laundary_Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laundary_Packges_Section_Title', models.CharField(blank=True, max_length=50)),
                ('Laundary_Packges_Section_Info', models.CharField(blank=True, max_length=100)),
                ('plan_title', models.CharField(blank=True, max_length=20)),
                ('plan_info', models.CharField(blank=True, max_length=100)),
                ('plan_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('plan_icon', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Laundary Packages',
            },
        ),
    ]
