# Generated by Django 5.0.6 on 2025-01-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundary_packages',
            name='Laundary_Packges_Section_Info',
        ),
        migrations.RemoveField(
            model_name='laundary_packages',
            name='Laundary_Packges_Section_Title',
        ),
    ]
