# Generated by Django 5.0.6 on 2025-01-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0002_remove_laundary_packages_laundary_packges_section_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundary_packages',
            name='plan_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='laundary_packages',
            name='plan_title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
