# Generated by Django 5.0.6 on 2025-01-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0003_alter_laundary_packages_plan_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_category', models.CharField(blank=True, max_length=30)),
                ('plan_title', models.CharField(blank=True, max_length=30)),
                ('plan_info', models.CharField(blank=True, max_length=200)),
                ('plan_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('plan_icon', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Laundary Packages',
            },
        ),
        migrations.DeleteModel(
            name='Laundary_Packages',
        ),
    ]
