# Generated by Django 5.0.6 on 2025-01-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0004_packages_plan_delete_laundary_packages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages_plan',
            options={'verbose_name': '', 'verbose_name_plural': 'Packages Plan'},
        ),
    ]
