# Generated by Django 5.0.6 on 2025-01-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0005_alter_packages_plan_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages_plan',
            old_name='plan_category',
            new_name='category',
        ),
    ]
