# Generated by Django 5.0.6 on 2025-01-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0006_rename_plan_category_packages_plan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages_plan',
            name='GST',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
