# Generated by Django 5.0.6 on 2025-01-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0007_packages_plan_gst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages_plan',
            old_name='plan_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='packages_plan',
            old_name='plan_price',
            new_name='price',
        ),
    ]
