# Generated by Django 5.0.6 on 2025-01-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0008_rename_plan_title_packages_plan_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages_plan',
            old_name='plan_icon',
            new_name='image',
        ),
    ]
