# Generated by Django 5.0.6 on 2025-01-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0009_rename_plan_icon_packages_plan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages_plan',
            name='image',
            field=models.FileField(upload_to='Package_Plans/'),
        ),
    ]
