# Generated by Django 5.0.6 on 2025-01-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0010_alter_packages_plan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages_plan',
            name='plan_title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
