# Generated by Django 5.0.6 on 2025-01-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0011_packages_plan_plan_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages_plan',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
