# Generated by Django 5.0.6 on 2025-01-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0012_alter_packages_plan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages_plan',
            name='GST',
        ),
    ]
