# Generated by Django 5.0.6 on 2025-01-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe_Packages_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(blank=True, max_length=30)),
                ('plan_info', models.CharField(blank=True, max_length=200)),
                ('plan_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('plan_icon', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Shoe Packages',
            },
        ),
    ]
