# Generated by Django 5.0.6 on 2025-01-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoe_Packages_Plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe_packages_plan',
            name='plan_price',
            field=models.IntegerField(blank=True, max_length=6),
        ),
    ]
