# Generated by Django 5.0.6 on 2025-01-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='Site_Logo/')),
                ('GST', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
