# Generated by Django 5.0.6 on 2025-01-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_settings',
            name='GST',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
